name: Update Calendar Data

on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  fetch-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Fetch and parce ICS
        run: |
          node fetch-calendar.js
        working-directory: ./backend

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Updated calendar data" || exit 0
          git push
